paths:
  data_root_dir: C:\Python projects\Datasets\Fine_tuning
  raw_data_dir: C:\Python projects\Datasets\train_test_split
  inference_images_dir: images\test
  inference_annotations_dir: labels\test

names:
  pt_model_name: yolo11n-seg.pt
  exported_model_name: yolo11n-seg_labeling.pt
  model_hyperparameters_file: model_cfg.json
  images_extensions: ['.jpg']
  labels_extensions: ['.txt']
  img_size: 1024

stages:
  - train_model
  - export_model
  - create_labelme_annotations
  - create_yolo_annotations
