name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: cmd

    - name: Set console encoding to UTF-8
      run: |
        chcp 65001
      shell: cmd

    - name: Debug directory structure
      run: |
        echo Current directory:
        cd
        echo List of files in src/tests:
        dir src\tests
      shell: cmd

    - name: Check Python version
      run: |
        python --version
      shell: cmd

    - name: Set PYTHONPATH
      run: |
        set PYTHONPATH=%PYTHONPATH%;%CD%\src
        echo PYTHONPATH=%PYTHONPATH%
      shell: cmd

    - name: Run tests
      run: |
        python -m unittest discover -s src/tests -p "test_*.py" -v
      shell: cmd